package model;
// Generated Aug 30, 2017 2:20:17 PM by Hibernate Tools 3.5.0.Final

/**
 * AccountSettingsId generated by hbm2java
 */
public class AccountSettingsId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3333228558566832187L;
	private String acAccount;
	private int sqAccountSettingVersion;

	public AccountSettingsId() {
	}

	public AccountSettingsId(String acAccount, int sqAccountSettingVersion) {
		this.acAccount = acAccount;
		this.sqAccountSettingVersion = sqAccountSettingVersion;
	}

	public String getAcAccount() {
		return this.acAccount;
	}

	public void setAcAccount(String acAccount) {
		this.acAccount = acAccount;
	}

	public int getSqAccountSettingVersion() {
		return this.sqAccountSettingVersion;
	}

	public void setSqAccountSettingVersion(int sqAccountSettingVersion) {
		this.sqAccountSettingVersion = sqAccountSettingVersion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AccountSettingsId))
			return false;
		AccountSettingsId castOther = (AccountSettingsId) other;

		return ((this.getAcAccount() == castOther.getAcAccount()) || (this.getAcAccount() != null
				&& castOther.getAcAccount() != null && this.getAcAccount().equals(castOther.getAcAccount())))
				&& (this.getSqAccountSettingVersion() == castOther.getSqAccountSettingVersion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAcAccount() == null ? 0 : this.getAcAccount().hashCode());
		result = 37 * result + this.getSqAccountSettingVersion();
		return result;
	}

}
