package model;
// Generated Aug 30, 2017 2:20:17 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * AccountSettings generated by hbm2java
 */
public class AccountSettings implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -2962315529189478308L;
	private AccountSettingsId id;
	private String acAccountType;
	private String dsAccount;
	private String acDefaultIban;
	private BigDecimal amChequeLimit;
	private Date dtSettingValidFrom;
	private Date dtSettingValidTo;
	private Date dtValidFrom;
	private Date dtValidTo;
	private String acCreationUser;
	private Date tsCreation;
	private String acLastUpdateUser;
	private Date tsLastUpdate;

	public AccountSettings() {
	}

	public AccountSettings(AccountSettingsId id, String acAccountType, String dsAccount, Date dtSettingValidFrom,
			Date dtSettingValidTo, Date dtValidFrom, Date dtValidTo, String acCreationUser, Date tsCreation,
			String acLastUpdateUser, Date tsLastUpdate) {
		this.id = id;
		this.acAccountType = acAccountType;
		this.dsAccount = dsAccount;
		this.dtSettingValidFrom = dtSettingValidFrom;
		this.dtSettingValidTo = dtSettingValidTo;
		this.dtValidFrom = dtValidFrom;
		this.dtValidTo = dtValidTo;
		this.acCreationUser = acCreationUser;
		this.tsCreation = tsCreation;
		this.acLastUpdateUser = acLastUpdateUser;
		this.tsLastUpdate = tsLastUpdate;
	}

	public AccountSettings(AccountSettingsId id, String acAccountType, String dsAccount, String acDefaultIban,
			BigDecimal amChequeLimit, Date dtSettingValidFrom, Date dtSettingValidTo, Date dtValidFrom, Date dtValidTo,
			String acCreationUser, Date tsCreation, String acLastUpdateUser, Date tsLastUpdate) {
		this.id = id;
		this.acAccountType = acAccountType;
		this.dsAccount = dsAccount;
		this.acDefaultIban = acDefaultIban;
		this.amChequeLimit = amChequeLimit;
		this.dtSettingValidFrom = dtSettingValidFrom;
		this.dtSettingValidTo = dtSettingValidTo;
		this.dtValidFrom = dtValidFrom;
		this.dtValidTo = dtValidTo;
		this.acCreationUser = acCreationUser;
		this.tsCreation = tsCreation;
		this.acLastUpdateUser = acLastUpdateUser;
		this.tsLastUpdate = tsLastUpdate;
	}

	public AccountSettingsId getId() {
		return this.id;
	}

	public void setId(AccountSettingsId id) {
		this.id = id;
	}

	public String getAcAccountType() {
		return this.acAccountType;
	}

	public void setAcAccountType(String acAccountType) {
		this.acAccountType = acAccountType;
	}

	public String getDsAccount() {
		return this.dsAccount;
	}

	public void setDsAccount(String dsAccount) {
		this.dsAccount = dsAccount;
	}

	public String getAcDefaultIban() {
		return this.acDefaultIban;
	}

	public void setAcDefaultIban(String acDefaultIban) {
		this.acDefaultIban = acDefaultIban;
	}

	public BigDecimal getAmChequeLimit() {
		return this.amChequeLimit;
	}

	public void setAmChequeLimit(BigDecimal amChequeLimit) {
		this.amChequeLimit = amChequeLimit;
	}

	public Date getDtSettingValidFrom() {
		return this.dtSettingValidFrom;
	}

	public void setDtSettingValidFrom(Date dtSettingValidFrom) {
		this.dtSettingValidFrom = dtSettingValidFrom;
	}

	public Date getDtSettingValidTo() {
		return this.dtSettingValidTo;
	}

	public void setDtSettingValidTo(Date dtSettingValidTo) {
		this.dtSettingValidTo = dtSettingValidTo;
	}

	public Date getDtValidFrom() {
		return this.dtValidFrom;
	}

	public void setDtValidFrom(Date dtValidFrom) {
		this.dtValidFrom = dtValidFrom;
	}

	public Date getDtValidTo() {
		return this.dtValidTo;
	}

	public void setDtValidTo(Date dtValidTo) {
		this.dtValidTo = dtValidTo;
	}

	public String getAcCreationUser() {
		return this.acCreationUser;
	}

	public void setAcCreationUser(String acCreationUser) {
		this.acCreationUser = acCreationUser;
	}

	public Date getTsCreation() {
		return this.tsCreation;
	}

	public void setTsCreation(Date tsCreation) {
		this.tsCreation = tsCreation;
	}

	public String getAcLastUpdateUser() {
		return this.acLastUpdateUser;
	}

	public void setAcLastUpdateUser(String acLastUpdateUser) {
		this.acLastUpdateUser = acLastUpdateUser;
	}

	public Date getTsLastUpdate() {
		return this.tsLastUpdate;
	}

	public void setTsLastUpdate(Date tsLastUpdate) {
		this.tsLastUpdate = tsLastUpdate;
	}

}
