package model;
// Generated Aug 29, 2017 4:11:15 PM by Hibernate Tools 3.5.0.Final

/**
 * BalanceId generated by hbm2java
 */
public class BalanceId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5344227702317991478L;
	private String acAccount;
	private String acBalanceType;
	private String acBalanceSubtype;
	private int ydBalance;
	private int mdBalance;

	public BalanceId() {
	}

	public BalanceId(String acAccount, String acBalanceType, String acBalanceSubtype, int ydBalance, int mdBalance) {
		this.acAccount = acAccount;
		this.acBalanceType = acBalanceType;
		this.acBalanceSubtype = acBalanceSubtype;
		this.ydBalance = ydBalance;
		this.mdBalance = mdBalance;
	}

	public String getAcAccount() {
		return this.acAccount;
	}

	public void setAcAccount(String acAccount) {
		this.acAccount = acAccount;
	}

	public String getAcBalanceType() {
		return this.acBalanceType;
	}

	public void setAcBalanceType(String acBalanceType) {
		this.acBalanceType = acBalanceType;
	}

	public String getAcBalanceSubtype() {
		return this.acBalanceSubtype;
	}

	public void setAcBalanceSubtype(String acBalanceSubtype) {
		this.acBalanceSubtype = acBalanceSubtype;
	}

	public int getYdBalance() {
		return this.ydBalance;
	}

	public void setYdBalance(int ydBalance) {
		this.ydBalance = ydBalance;
	}

	public int getMdBalance() {
		return this.mdBalance;
	}

	public void setMdBalance(int mdBalance) {
		this.mdBalance = mdBalance;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof BalanceId))
			return false;
		BalanceId castOther = (BalanceId) other;

		return ((this.getAcAccount() == castOther.getAcAccount()) || (this.getAcAccount() != null
				&& castOther.getAcAccount() != null && this.getAcAccount().equals(castOther.getAcAccount())))
				&& ((this.getAcBalanceType() == castOther.getAcBalanceType())
						|| (this.getAcBalanceType() != null && castOther.getAcBalanceType() != null
								&& this.getAcBalanceType().equals(castOther.getAcBalanceType())))
				&& ((this.getAcBalanceSubtype() == castOther.getAcBalanceSubtype())
						|| (this.getAcBalanceSubtype() != null && castOther.getAcBalanceSubtype() != null
								&& this.getAcBalanceSubtype().equals(castOther.getAcBalanceSubtype())))
				&& (this.getYdBalance() == castOther.getYdBalance())
				&& (this.getMdBalance() == castOther.getMdBalance());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAcAccount() == null ? 0 : this.getAcAccount().hashCode());
		result = 37 * result + (getAcBalanceType() == null ? 0 : this.getAcBalanceType().hashCode());
		result = 37 * result + (getAcBalanceSubtype() == null ? 0 : this.getAcBalanceSubtype().hashCode());
		result = 37 * result + this.getYdBalance();
		result = 37 * result + this.getMdBalance();
		return result;
	}

}
