package model;
// Generated Aug 30, 2017 2:20:17 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Cheque generated by hbm2java
 */
public class Cheque implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6053761179192647268L;
	private ChequeId id;
	private String acChequeZib;
	private int sqOperation;
	private BigDecimal amCheque;
	private String acCurrency;
	private String acOriginalChequeZib;
	private String acOriginalChequeAcctNumber;
	private String acOriginalChequeNumber;
	private String acOriginCashierAccount;
	private String acDestinationCashierAccount;
	private int niChequeSubstitutions;
	private String acChequeStatus;
	private int sqObservation;
	private int fgCurrentVersion;
	private Date dtValidFrom;
	private Date dtValidTo;
	private String acCreationUser;
	private Date tsCreation;
	private String acLastUpdateUser;
	private Date tsLastUpdate;

	public Cheque() {
	}

	public Cheque(ChequeId id, String acChequeZib, int sqOperation, BigDecimal amCheque, String acCurrency,
			int niChequeSubstitutions, String acChequeStatus, int fgCurrentVersion, String acCreationUser,
			Date tsCreation, String acLastUpdateUser, Date tsLastUpdate) {
		this.id = id;
		this.acChequeZib = acChequeZib;
		this.sqOperation = sqOperation;
		this.amCheque = amCheque;
		this.acCurrency = acCurrency;
		this.niChequeSubstitutions = niChequeSubstitutions;
		this.acChequeStatus = acChequeStatus;
		this.fgCurrentVersion = fgCurrentVersion;
		this.acCreationUser = acCreationUser;
		this.tsCreation = tsCreation;
		this.acLastUpdateUser = acLastUpdateUser;
		this.tsLastUpdate = tsLastUpdate;
	}

	public Cheque(ChequeId id, String acChequeZib, int sqOperation, BigDecimal amCheque, String acCurrency,
			String acOriginalChequeZib, String acOriginalChequeAcctNumber, String acOriginalChequeNumber,
			String acOriginCashierAccount, String acDestinationCashierAccount, int niChequeSubstitutions,
			String acChequeStatus, int sqObservation, int fgCurrentVersion, Date dtValidFrom, Date dtValidTo,
			String acCreationUser, Date tsCreation, String acLastUpdateUser, Date tsLastUpdate) {
		this.id = id;
		this.acChequeZib = acChequeZib;
		this.sqOperation = sqOperation;
		this.amCheque = amCheque;
		this.acCurrency = acCurrency;
		this.acOriginalChequeZib = acOriginalChequeZib;
		this.acOriginalChequeAcctNumber = acOriginalChequeAcctNumber;
		this.acOriginalChequeNumber = acOriginalChequeNumber;
		this.acOriginCashierAccount = acOriginCashierAccount;
		this.acDestinationCashierAccount = acDestinationCashierAccount;
		this.niChequeSubstitutions = niChequeSubstitutions;
		this.acChequeStatus = acChequeStatus;
		this.sqObservation = sqObservation;
		this.fgCurrentVersion = fgCurrentVersion;
		this.dtValidFrom = dtValidFrom;
		this.dtValidTo = dtValidTo;
		this.acCreationUser = acCreationUser;
		this.tsCreation = tsCreation;
		this.acLastUpdateUser = acLastUpdateUser;
		this.tsLastUpdate = tsLastUpdate;
	}

	public ChequeId getId() {
		return this.id;
	}

	public void setId(ChequeId id) {
		this.id = id;
	}

	public String getAcChequeZib() {
		return this.acChequeZib;
	}

	public void setAcChequeZib(String acChequeZib) {
		this.acChequeZib = acChequeZib;
	}

	public int getSqOperation() {
		return this.sqOperation;
	}

	public void setSqOperation(int sqOperation) {
		this.sqOperation = sqOperation;
	}

	public BigDecimal getAmCheque() {
		return this.amCheque;
	}

	public void setAmCheque(BigDecimal amCheque) {
		this.amCheque = amCheque;
	}

	public String getAcCurrency() {
		return this.acCurrency;
	}

	public void setAcCurrency(String acCurrency) {
		this.acCurrency = acCurrency;
	}

	public String getAcOriginalChequeZib() {
		return this.acOriginalChequeZib;
	}

	public void setAcOriginalChequeZib(String acOriginalChequeZib) {
		this.acOriginalChequeZib = acOriginalChequeZib;
	}

	public String getAcOriginalChequeAcctNumber() {
		return this.acOriginalChequeAcctNumber;
	}

	public void setAcOriginalChequeAcctNumber(String acOriginalChequeAcctNumber) {
		this.acOriginalChequeAcctNumber = acOriginalChequeAcctNumber;
	}

	public String getAcOriginalChequeNumber() {
		return this.acOriginalChequeNumber;
	}

	public void setAcOriginalChequeNumber(String acOriginalChequeNumber) {
		this.acOriginalChequeNumber = acOriginalChequeNumber;
	}

	public String getAcOriginCashierAccount() {
		return this.acOriginCashierAccount;
	}

	public void setAcOriginCashierAccount(String acOriginCashierAccount) {
		this.acOriginCashierAccount = acOriginCashierAccount;
	}

	public String getAcDestinationCashierAccount() {
		return this.acDestinationCashierAccount;
	}

	public void setAcDestinationCashierAccount(String acDestinationCashierAccount) {
		this.acDestinationCashierAccount = acDestinationCashierAccount;
	}

	public int getNiChequeSubstitutions() {
		return this.niChequeSubstitutions;
	}

	public void setNiChequeSubstitutions(int niChequeSubstitutions) {
		this.niChequeSubstitutions = niChequeSubstitutions;
	}

	public String getAcChequeStatus() {
		return this.acChequeStatus;
	}

	public void setAcChequeStatus(String acChequeStatus) {
		this.acChequeStatus = acChequeStatus;
	}

	public int getSqObservation() {
		return this.sqObservation;
	}

	public void setSqObservation(int sqObservation) {
		this.sqObservation = sqObservation;
	}

	public int getFgCurrentVersion() {
		return this.fgCurrentVersion;
	}

	public void setFgCurrentVersion(int fgCurrentVersion) {
		this.fgCurrentVersion = fgCurrentVersion;
	}

	public Date getDtValidFrom() {
		return this.dtValidFrom;
	}

	public void setDtValidFrom(Date dtValidFrom) {
		this.dtValidFrom = dtValidFrom;
	}

	public Date getDtValidTo() {
		return this.dtValidTo;
	}

	public void setDtValidTo(Date dtValidTo) {
		this.dtValidTo = dtValidTo;
	}

	public String getAcCreationUser() {
		return this.acCreationUser;
	}

	public void setAcCreationUser(String acCreationUser) {
		this.acCreationUser = acCreationUser;
	}

	public Date getTsCreation() {
		return this.tsCreation;
	}

	public void setTsCreation(Date tsCreation) {
		this.tsCreation = tsCreation;
	}

	public String getAcLastUpdateUser() {
		return this.acLastUpdateUser;
	}

	public void setAcLastUpdateUser(String acLastUpdateUser) {
		this.acLastUpdateUser = acLastUpdateUser;
	}

	public Date getTsLastUpdate() {
		return this.tsLastUpdate;
	}

	public void setTsLastUpdate(Date tsLastUpdate) {
		this.tsLastUpdate = tsLastUpdate;
	}

}
