package model;
// Generated Aug 29, 2017 4:11:15 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Commission generated by hbm2java
 */
public class Commission implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4499440269386227466L;
	private CommissionId id;
	private String acCompany;
	private int sqOperation;
	private String acCommissionType;
	private int sqReceipt;
	private BigDecimal amCommission;
	private String acCurrency;
	private int sqObservation;
	private Date dtValidFrom;
	private Date dtValidTo;
	private int fgCurrentVersion;
	private String acCreationUser;
	private Date tsCreation;
	private String acLastUpdateUser;
	private Date tsLastUpdate;

	public Commission() {
	}

	public Commission(CommissionId id, int sqOperation, int sqReceipt, int fgCurrentVersion, String acCreationUser,
			Date tsCreation, String acLastUpdateUser, Date tsLastUpdate) {
		this.id = id;
		this.sqOperation = sqOperation;
		this.sqReceipt = sqReceipt;
		this.fgCurrentVersion = fgCurrentVersion;
		this.acCreationUser = acCreationUser;
		this.tsCreation = tsCreation;
		this.acLastUpdateUser = acLastUpdateUser;
		this.tsLastUpdate = tsLastUpdate;
	}

	public Commission(CommissionId id, String acCompany, int sqOperation, String acCommissionType, int sqReceipt,
			BigDecimal amCommission, String acCurrency, int sqObservation, Date dtValidFrom, Date dtValidTo,
			int fgCurrentVersion, String acCreationUser, Date tsCreation, String acLastUpdateUser, Date tsLastUpdate) {
		this.id = id;
		this.acCompany = acCompany;
		this.sqOperation = sqOperation;
		this.acCommissionType = acCommissionType;
		this.sqReceipt = sqReceipt;
		this.amCommission = amCommission;
		this.acCurrency = acCurrency;
		this.sqObservation = sqObservation;
		this.dtValidFrom = dtValidFrom;
		this.dtValidTo = dtValidTo;
		this.fgCurrentVersion = fgCurrentVersion;
		this.acCreationUser = acCreationUser;
		this.tsCreation = tsCreation;
		this.acLastUpdateUser = acLastUpdateUser;
		this.tsLastUpdate = tsLastUpdate;
	}

	public CommissionId getId() {
		return this.id;
	}

	public void setId(CommissionId id) {
		this.id = id;
	}

	public String getAcCompany() {
		return this.acCompany;
	}

	public void setAcCompany(String acCompany) {
		this.acCompany = acCompany;
	}

	public int getSqOperation() {
		return this.sqOperation;
	}

	public void setSqOperation(int sqOperation) {
		this.sqOperation = sqOperation;
	}

	public String getAcCommissionType() {
		return this.acCommissionType;
	}

	public void setAcCommissionType(String acCommissionType) {
		this.acCommissionType = acCommissionType;
	}

	public int getSqReceipt() {
		return this.sqReceipt;
	}

	public void setSqReceipt(int sqReceipt) {
		this.sqReceipt = sqReceipt;
	}

	public BigDecimal getAmCommission() {
		return this.amCommission;
	}

	public void setAmCommission(BigDecimal amCommission) {
		this.amCommission = amCommission;
	}

	public String getAcCurrency() {
		return this.acCurrency;
	}

	public void setAcCurrency(String acCurrency) {
		this.acCurrency = acCurrency;
	}

	public int getSqObservation() {
		return this.sqObservation;
	}

	public void setSqObservation(int sqObservation) {
		this.sqObservation = sqObservation;
	}

	public Date getDtValidFrom() {
		return this.dtValidFrom;
	}

	public void setDtValidFrom(Date dtValidFrom) {
		this.dtValidFrom = dtValidFrom;
	}

	public Date getDtValidTo() {
		return this.dtValidTo;
	}

	public void setDtValidTo(Date dtValidTo) {
		this.dtValidTo = dtValidTo;
	}

	public int getFgCurrentVersion() {
		return this.fgCurrentVersion;
	}

	public void setFgCurrentVersion(int fgCurrentVersion) {
		this.fgCurrentVersion = fgCurrentVersion;
	}

	public String getAcCreationUser() {
		return this.acCreationUser;
	}

	public void setAcCreationUser(String acCreationUser) {
		this.acCreationUser = acCreationUser;
	}

	public Date getTsCreation() {
		return this.tsCreation;
	}

	public void setTsCreation(Date tsCreation) {
		this.tsCreation = tsCreation;
	}

	public String getAcLastUpdateUser() {
		return this.acLastUpdateUser;
	}

	public void setAcLastUpdateUser(String acLastUpdateUser) {
		this.acLastUpdateUser = acLastUpdateUser;
	}

	public Date getTsLastUpdate() {
		return this.tsLastUpdate;
	}

	public void setTsLastUpdate(Date tsLastUpdate) {
		this.tsLastUpdate = tsLastUpdate;
	}

}
