package model;
// Generated Aug 29, 2017 4:11:15 PM by Hibernate Tools 3.5.0.Final

/**
 * CommissionId generated by hbm2java
 */
public class CommissionId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5333282824207289349L;
	private int sqCommission;
	private int sqCommissionVersion;

	public CommissionId() {
	}

	public CommissionId(int sqCommission, int sqCommissionVersion) {
		this.sqCommission = sqCommission;
		this.sqCommissionVersion = sqCommissionVersion;
	}

	public int getSqCommission() {
		return this.sqCommission;
	}

	public void setSqCommission(int sqCommission) {
		this.sqCommission = sqCommission;
	}

	public int getSqCommissionVersion() {
		return this.sqCommissionVersion;
	}

	public void setSqCommissionVersion(int sqCommissionVersion) {
		this.sqCommissionVersion = sqCommissionVersion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CommissionId))
			return false;
		CommissionId castOther = (CommissionId) other;

		return (this.getSqCommission() == castOther.getSqCommission())
				&& (this.getSqCommissionVersion() == castOther.getSqCommissionVersion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSqCommission();
		result = 37 * result + this.getSqCommissionVersion();
		return result;
	}

}
