package model;
// Generated Aug 30, 2017 2:20:17 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Cover generated by hbm2java
 */
public class Cover implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7815663559653678945L;
	private int sqCover;
	private String acCoverType;
	private String acCompany;
	private int sqReceipt;
	private int sqOperation;
	private BigDecimal amInsured;
	private String acCreationUser;
	private Date tsCreation;
	private String acLastUpdateUser;
	private Date tsLastUpdate;

	public Cover() {
	}

	public Cover(int sqCover, String acCreationUser, Date tsCreation, String acLastUpdateUser, Date tsLastUpdate) {
		this.sqCover = sqCover;
		this.acCreationUser = acCreationUser;
		this.tsCreation = tsCreation;
		this.acLastUpdateUser = acLastUpdateUser;
		this.tsLastUpdate = tsLastUpdate;
	}

	public Cover(int sqCover, String acCoverType, String acCompany, int sqReceipt, int sqOperation,
			BigDecimal amInsured, String acCreationUser, Date tsCreation, String acLastUpdateUser, Date tsLastUpdate) {
		this.sqCover = sqCover;
		this.acCoverType = acCoverType;
		this.acCompany = acCompany;
		this.sqReceipt = sqReceipt;
		this.sqOperation = sqOperation;
		this.amInsured = amInsured;
		this.acCreationUser = acCreationUser;
		this.tsCreation = tsCreation;
		this.acLastUpdateUser = acLastUpdateUser;
		this.tsLastUpdate = tsLastUpdate;
	}

	public int getSqCover() {
		return this.sqCover;
	}

	public void setSqCover(int sqCover) {
		this.sqCover = sqCover;
	}

	public String getAcCoverType() {
		return this.acCoverType;
	}

	public void setAcCoverType(String acCoverType) {
		this.acCoverType = acCoverType;
	}

	public String getAcCompany() {
		return this.acCompany;
	}

	public void setAcCompany(String acCompany) {
		this.acCompany = acCompany;
	}

	public int getSqReceipt() {
		return this.sqReceipt;
	}

	public void setSqReceipt(int sqReceipt) {
		this.sqReceipt = sqReceipt;
	}

	public int getSqOperation() {
		return this.sqOperation;
	}

	public void setSqOperation(int sqOperation) {
		this.sqOperation = sqOperation;
	}

	public BigDecimal getAmInsured() {
		return this.amInsured;
	}

	public void setAmInsured(BigDecimal amInsured) {
		this.amInsured = amInsured;
	}

	public String getAcCreationUser() {
		return this.acCreationUser;
	}

	public void setAcCreationUser(String acCreationUser) {
		this.acCreationUser = acCreationUser;
	}

	public Date getTsCreation() {
		return this.tsCreation;
	}

	public void setTsCreation(Date tsCreation) {
		this.tsCreation = tsCreation;
	}

	public String getAcLastUpdateUser() {
		return this.acLastUpdateUser;
	}

	public void setAcLastUpdateUser(String acLastUpdateUser) {
		this.acLastUpdateUser = acLastUpdateUser;
	}

	public Date getTsLastUpdate() {
		return this.tsLastUpdate;
	}

	public void setTsLastUpdate(Date tsLastUpdate) {
		this.tsLastUpdate = tsLastUpdate;
	}

}
