package model;
// Generated Aug 30, 2017 2:20:17 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * Observation generated by hbm2java
 */
public class Observation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 7665109693728087463L;
	private int sqObservation;
	private String acTableName;
	private String acType;
	private String dsObservation;
	private String acCreationUser;
	private Date tsCreation;
	private String acLastUpdateUser;
	private Date tsLastUpdate;

	public Observation() {
	}

	public Observation(int sqObservation, String acTableName, String acType, String dsObservation,
			String acCreationUser, Date tsCreation, String acLastUpdateUser, Date tsLastUpdate) {
		this.sqObservation = sqObservation;
		this.acTableName = acTableName;
		this.acType = acType;
		this.dsObservation = dsObservation;
		this.acCreationUser = acCreationUser;
		this.tsCreation = tsCreation;
		this.acLastUpdateUser = acLastUpdateUser;
		this.tsLastUpdate = tsLastUpdate;
	}

	public int getSqObservation() {
		return this.sqObservation;
	}

	public void setSqObservation(int sqObservation) {
		this.sqObservation = sqObservation;
	}

	public String getAcTableName() {
		return this.acTableName;
	}

	public void setAcTableName(String acTableName) {
		this.acTableName = acTableName;
	}

	public String getAcType() {
		return this.acType;
	}

	public void setAcType(String acType) {
		this.acType = acType;
	}

	public String getDsObservation() {
		return this.dsObservation;
	}

	public void setDsObservation(String dsObservation) {
		this.dsObservation = dsObservation;
	}

	public String getAcCreationUser() {
		return this.acCreationUser;
	}

	public void setAcCreationUser(String acCreationUser) {
		this.acCreationUser = acCreationUser;
	}

	public Date getTsCreation() {
		return this.tsCreation;
	}

	public void setTsCreation(Date tsCreation) {
		this.tsCreation = tsCreation;
	}

	public String getAcLastUpdateUser() {
		return this.acLastUpdateUser;
	}

	public void setAcLastUpdateUser(String acLastUpdateUser) {
		this.acLastUpdateUser = acLastUpdateUser;
	}

	public Date getTsLastUpdate() {
		return this.tsLastUpdate;
	}

	public void setTsLastUpdate(Date tsLastUpdate) {
		this.tsLastUpdate = tsLastUpdate;
	}

}
