package model;
// Generated Aug 30, 2017 2:20:17 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.Date;

/**
 * Operation generated by hbm2java
 */
public class Operation implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7163164292338132061L;
	private int sqOperation;
	private String acOperationType;
	private Date dtOperation;
	private String acOperationStatus;
	private BigDecimal amOperation;
	private int sqObservation;
	private String acCreationUser;
	private Date tsCreation;
	private String acLastUpdateUser;
	private Date tsLastUpdate;

	public Operation() {
	}

	public Operation(int sqOperation, String acOperationType, Date dtOperation, String acCreationUser, Date tsCreation,
			String acLastUpdateUser, Date tsLastUpdate) {
		this.sqOperation = sqOperation;
		this.acOperationType = acOperationType;
		this.dtOperation = dtOperation;
		this.acCreationUser = acCreationUser;
		this.tsCreation = tsCreation;
		this.acLastUpdateUser = acLastUpdateUser;
		this.tsLastUpdate = tsLastUpdate;
	}

	public Operation(int sqOperation, String acOperationType, Date dtOperation, String acOperationStatus,
			BigDecimal amOperation, int sqObservation, String acCreationUser, Date tsCreation, String acLastUpdateUser,
			Date tsLastUpdate) {
		this.sqOperation = sqOperation;
		this.acOperationType = acOperationType;
		this.dtOperation = dtOperation;
		this.acOperationStatus = acOperationStatus;
		this.amOperation = amOperation;
		this.sqObservation = sqObservation;
		this.acCreationUser = acCreationUser;
		this.tsCreation = tsCreation;
		this.acLastUpdateUser = acLastUpdateUser;
		this.tsLastUpdate = tsLastUpdate;
	}

	public int getSqOperation() {
		return this.sqOperation;
	}

	public void setSqOperation(int sqOperation) {
		this.sqOperation = sqOperation;
	}

	public String getAcOperationType() {
		return this.acOperationType;
	}

	public void setAcOperationType(String acOperationType) {
		this.acOperationType = acOperationType;
	}

	public Date getDtOperation() {
		return this.dtOperation;
	}

	public void setDtOperation(Date dtOperation) {
		this.dtOperation = dtOperation;
	}

	public String getAcOperationStatus() {
		return this.acOperationStatus;
	}

	public void setAcOperationStatus(String acOperationStatus) {
		this.acOperationStatus = acOperationStatus;
	}

	public BigDecimal getAmOperation() {
		return this.amOperation;
	}

	public void setAmOperation(BigDecimal amOperation) {
		this.amOperation = amOperation;
	}

	public int getSqObservation() {
		return this.sqObservation;
	}

	public void setSqObservation(int sqObservation) {
		this.sqObservation = sqObservation;
	}

	public String getAcCreationUser() {
		return this.acCreationUser;
	}

	public void setAcCreationUser(String acCreationUser) {
		this.acCreationUser = acCreationUser;
	}

	public Date getTsCreation() {
		return this.tsCreation;
	}

	public void setTsCreation(Date tsCreation) {
		this.tsCreation = tsCreation;
	}

	public String getAcLastUpdateUser() {
		return this.acLastUpdateUser;
	}

	public void setAcLastUpdateUser(String acLastUpdateUser) {
		this.acLastUpdateUser = acLastUpdateUser;
	}

	public Date getTsLastUpdate() {
		return this.tsLastUpdate;
	}

	public void setTsLastUpdate(Date tsLastUpdate) {
		this.tsLastUpdate = tsLastUpdate;
	}

}
