package model;
// Generated Aug 29, 2017 4:11:15 PM by Hibernate Tools 3.5.0.Final

/**
 * ReceiptStatusId generated by hbm2java
 */
public class ReceiptStatusId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3295686472867981971L;
	private int sqReceipt;
	private int sqReceiptVersion;

	public ReceiptStatusId() {
	}

	public ReceiptStatusId(int sqReceipt, int sqReceiptVersion) {
		this.sqReceipt = sqReceipt;
		this.sqReceiptVersion = sqReceiptVersion;
	}

	public int getSqReceipt() {
		return this.sqReceipt;
	}

	public void setSqReceipt(int sqReceipt) {
		this.sqReceipt = sqReceipt;
	}

	public int getSqReceiptVersion() {
		return this.sqReceiptVersion;
	}

	public void setSqReceiptVersion(int sqReceiptVersion) {
		this.sqReceiptVersion = sqReceiptVersion;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReceiptStatusId))
			return false;
		ReceiptStatusId castOther = (ReceiptStatusId) other;

		return (this.getSqReceipt() == castOther.getSqReceipt())
				&& (this.getSqReceiptVersion() == castOther.getSqReceiptVersion());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getSqReceipt();
		result = 37 * result + this.getSqReceiptVersion();
		return result;
	}

}
