package model;
// Generated Aug 30, 2017 2:20:17 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * ReceiptCollection generated by hbm2java
 */
public class ReceiptCollection implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4651525368536670885L;
	private int sqReceipt;
	private String dsAddress;
	private String dsPostalCode;
	private String dsCityName;
	private String dsCountyName;
	private String acCountry;
	private String acCollectLetterType;
	private String acCreationUser;
	private Date tsCreation;
	private String acLastUpdateUser;
	private Date tsLastUpdate;

	public ReceiptCollection() {
	}

	public ReceiptCollection(int sqReceipt, String acCreationUser, Date tsCreation, String acLastUpdateUser,
			Date tsLastUpdate) {
		this.sqReceipt = sqReceipt;
		this.acCreationUser = acCreationUser;
		this.tsCreation = tsCreation;
		this.acLastUpdateUser = acLastUpdateUser;
		this.tsLastUpdate = tsLastUpdate;
	}

	public ReceiptCollection(int sqReceipt, String dsAddress, String dsPostalCode, String dsCityName,
			String dsCountyName, String acCountry, String acCollectLetterType, String acCreationUser, Date tsCreation,
			String acLastUpdateUser, Date tsLastUpdate) {
		this.sqReceipt = sqReceipt;
		this.dsAddress = dsAddress;
		this.dsPostalCode = dsPostalCode;
		this.dsCityName = dsCityName;
		this.dsCountyName = dsCountyName;
		this.acCountry = acCountry;
		this.acCollectLetterType = acCollectLetterType;
		this.acCreationUser = acCreationUser;
		this.tsCreation = tsCreation;
		this.acLastUpdateUser = acLastUpdateUser;
		this.tsLastUpdate = tsLastUpdate;
	}

	public int getSqReceipt() {
		return this.sqReceipt;
	}

	public void setSqReceipt(int sqReceipt) {
		this.sqReceipt = sqReceipt;
	}

	public String getDsAddress() {
		return this.dsAddress;
	}

	public void setDsAddress(String dsAddress) {
		this.dsAddress = dsAddress;
	}

	public String getDsPostalCode() {
		return this.dsPostalCode;
	}

	public void setDsPostalCode(String dsPostalCode) {
		this.dsPostalCode = dsPostalCode;
	}

	public String getDsCityName() {
		return this.dsCityName;
	}

	public void setDsCityName(String dsCityName) {
		this.dsCityName = dsCityName;
	}

	public String getDsCountyName() {
		return this.dsCountyName;
	}

	public void setDsCountyName(String dsCountyName) {
		this.dsCountyName = dsCountyName;
	}

	public String getAcCountry() {
		return this.acCountry;
	}

	public void setAcCountry(String acCountry) {
		this.acCountry = acCountry;
	}

	public String getAcCollectLetterType() {
		return this.acCollectLetterType;
	}

	public void setAcCollectLetterType(String acCollectLetterType) {
		this.acCollectLetterType = acCollectLetterType;
	}

	public String getAcCreationUser() {
		return this.acCreationUser;
	}

	public void setAcCreationUser(String acCreationUser) {
		this.acCreationUser = acCreationUser;
	}

	public Date getTsCreation() {
		return this.tsCreation;
	}

	public void setTsCreation(Date tsCreation) {
		this.tsCreation = tsCreation;
	}

	public String getAcLastUpdateUser() {
		return this.acLastUpdateUser;
	}

	public void setAcLastUpdateUser(String acLastUpdateUser) {
		this.acLastUpdateUser = acLastUpdateUser;
	}

	public Date getTsLastUpdate() {
		return this.tsLastUpdate;
	}

	public void setTsLastUpdate(Date tsLastUpdate) {
		this.tsLastUpdate = tsLastUpdate;
	}

}
