package model;
// Generated Aug 30, 2017 2:20:17 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * ReceiptStatus generated by hbm2java
 */
public class ReceiptStatus implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5676051724802164164L;
	private ReceiptStatusId id;
	private int sqOperation;
	private String acOperationType;
	private String acBranch;
	private String acProduct;
	private String acPolicyNumber;
	private String acOriginalPaymentType;
	private String acPaymentType;
	private String acClaimNumber;
	private String acReceiptStatus;
	private String acReceiptStatusMotive;
	private int sqObservation;
	private String acOperationAccount;
	private String acIban;
	private String acExternalReference;
	private int fgCurrentVersion;
	private Date dtValidFrom;
	private Date dtValidTo;
	private String acCollectionUserCode;
	private String acBic;
	private String acCreationUser;
	private Date tsCreation;
	private String acLastUpdateUser;
	private Date tsLastUpdate;

	public ReceiptStatus() {
	}

	public ReceiptStatus(ReceiptStatusId id, int sqOperation, String acOperationType, String acBranch, String acProduct,
			String acOriginalPaymentType, String acPaymentType, String acReceiptStatus, String acReceiptStatusMotive,
			int fgCurrentVersion, Date dtValidFrom, Date dtValidTo, String acCreationUser, Date tsCreation,
			String acLastUpdateUser, Date tsLastUpdate) {
		this.id = id;
		this.sqOperation = sqOperation;
		this.acOperationType = acOperationType;
		this.acBranch = acBranch;
		this.acProduct = acProduct;
		this.acOriginalPaymentType = acOriginalPaymentType;
		this.acPaymentType = acPaymentType;
		this.acReceiptStatus = acReceiptStatus;
		this.acReceiptStatusMotive = acReceiptStatusMotive;
		this.fgCurrentVersion = fgCurrentVersion;
		this.dtValidFrom = dtValidFrom;
		this.dtValidTo = dtValidTo;
		this.acCreationUser = acCreationUser;
		this.tsCreation = tsCreation;
		this.acLastUpdateUser = acLastUpdateUser;
		this.tsLastUpdate = tsLastUpdate;
	}

	public ReceiptStatus(ReceiptStatusId id, int sqOperation, String acOperationType, String acBranch, String acProduct,
			String acPolicyNumber, String acOriginalPaymentType, String acPaymentType, String acClaimNumber,
			String acReceiptStatus, String acReceiptStatusMotive, int sqObservation, String acOperationAccount,
			String acIban, String acExternalReference, int fgCurrentVersion, Date dtValidFrom, Date dtValidTo,
			String acCollectionUserCode, String acBic, String acCreationUser, Date tsCreation, String acLastUpdateUser,
			Date tsLastUpdate) {
		this.id = id;
		this.sqOperation = sqOperation;
		this.acOperationType = acOperationType;
		this.acBranch = acBranch;
		this.acProduct = acProduct;
		this.acPolicyNumber = acPolicyNumber;
		this.acOriginalPaymentType = acOriginalPaymentType;
		this.acPaymentType = acPaymentType;
		this.acClaimNumber = acClaimNumber;
		this.acReceiptStatus = acReceiptStatus;
		this.acReceiptStatusMotive = acReceiptStatusMotive;
		this.sqObservation = sqObservation;
		this.acOperationAccount = acOperationAccount;
		this.acIban = acIban;
		this.acExternalReference = acExternalReference;
		this.fgCurrentVersion = fgCurrentVersion;
		this.dtValidFrom = dtValidFrom;
		this.dtValidTo = dtValidTo;
		this.acCollectionUserCode = acCollectionUserCode;
		this.acBic = acBic;
		this.acCreationUser = acCreationUser;
		this.tsCreation = tsCreation;
		this.acLastUpdateUser = acLastUpdateUser;
		this.tsLastUpdate = tsLastUpdate;
	}

	public ReceiptStatusId getId() {
		return this.id;
	}

	public void setId(ReceiptStatusId id) {
		this.id = id;
	}

	public int getSqOperation() {
		return this.sqOperation;
	}

	public void setSqOperation(int sqOperation) {
		this.sqOperation = sqOperation;
	}

	public String getAcOperationType() {
		return this.acOperationType;
	}

	public void setAcOperationType(String acOperationType) {
		this.acOperationType = acOperationType;
	}

	public String getAcBranch() {
		return this.acBranch;
	}

	public void setAcBranch(String acBranch) {
		this.acBranch = acBranch;
	}

	public String getAcProduct() {
		return this.acProduct;
	}

	public void setAcProduct(String acProduct) {
		this.acProduct = acProduct;
	}

	public String getAcPolicyNumber() {
		return this.acPolicyNumber;
	}

	public void setAcPolicyNumber(String acPolicyNumber) {
		this.acPolicyNumber = acPolicyNumber;
	}

	public String getAcOriginalPaymentType() {
		return this.acOriginalPaymentType;
	}

	public void setAcOriginalPaymentType(String acOriginalPaymentType) {
		this.acOriginalPaymentType = acOriginalPaymentType;
	}

	public String getAcPaymentType() {
		return this.acPaymentType;
	}

	public void setAcPaymentType(String acPaymentType) {
		this.acPaymentType = acPaymentType;
	}

	public String getAcClaimNumber() {
		return this.acClaimNumber;
	}

	public void setAcClaimNumber(String acClaimNumber) {
		this.acClaimNumber = acClaimNumber;
	}

	public String getAcReceiptStatus() {
		return this.acReceiptStatus;
	}

	public void setAcReceiptStatus(String acReceiptStatus) {
		this.acReceiptStatus = acReceiptStatus;
	}

	public String getAcReceiptStatusMotive() {
		return this.acReceiptStatusMotive;
	}

	public void setAcReceiptStatusMotive(String acReceiptStatusMotive) {
		this.acReceiptStatusMotive = acReceiptStatusMotive;
	}

	public int getSqObservation() {
		return this.sqObservation;
	}

	public void setSqObservation(int sqObservation) {
		this.sqObservation = sqObservation;
	}

	public String getAcOperationAccount() {
		return this.acOperationAccount;
	}

	public void setAcOperationAccount(String acOperationAccount) {
		this.acOperationAccount = acOperationAccount;
	}

	public String getAcIban() {
		return this.acIban;
	}

	public void setAcIban(String acIban) {
		this.acIban = acIban;
	}

	public String getAcExternalReference() {
		return this.acExternalReference;
	}

	public void setAcExternalReference(String acExternalReference) {
		this.acExternalReference = acExternalReference;
	}

	public int getFgCurrentVersion() {
		return this.fgCurrentVersion;
	}

	public void setFgCurrentVersion(int fgCurrentVersion) {
		this.fgCurrentVersion = fgCurrentVersion;
	}

	public Date getDtValidFrom() {
		return this.dtValidFrom;
	}

	public void setDtValidFrom(Date dtValidFrom) {
		this.dtValidFrom = dtValidFrom;
	}

	public Date getDtValidTo() {
		return this.dtValidTo;
	}

	public void setDtValidTo(Date dtValidTo) {
		this.dtValidTo = dtValidTo;
	}

	public String getAcCollectionUserCode() {
		return this.acCollectionUserCode;
	}

	public void setAcCollectionUserCode(String acCollectionUserCode) {
		this.acCollectionUserCode = acCollectionUserCode;
	}

	public String getAcBic() {
		return this.acBic;
	}

	public void setAcBic(String acBic) {
		this.acBic = acBic;
	}

	public String getAcCreationUser() {
		return this.acCreationUser;
	}

	public void setAcCreationUser(String acCreationUser) {
		this.acCreationUser = acCreationUser;
	}

	public Date getTsCreation() {
		return this.tsCreation;
	}

	public void setTsCreation(Date tsCreation) {
		this.tsCreation = tsCreation;
	}

	public String getAcLastUpdateUser() {
		return this.acLastUpdateUser;
	}

	public void setAcLastUpdateUser(String acLastUpdateUser) {
		this.acLastUpdateUser = acLastUpdateUser;
	}

	public Date getTsLastUpdate() {
		return this.tsLastUpdate;
	}

	public void setTsLastUpdate(Date tsLastUpdate) {
		this.tsLastUpdate = tsLastUpdate;
	}

}
