package model;
// Generated Aug 30, 2017 2:20:17 PM by Hibernate Tools 3.5.0.Final

import java.util.Date;

/**
 * ReferenceDataId generated by hbm2java
 */
public class ReferenceDataId implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -1847622111185194674L;
	private String acLogicalTable;
	private String acElement;
	private String dsElement;
	private String acCreationUser;
	private Date tsCreation;
	private String acLastUpdateUser;
	private Date tsLastUpdate;

	public ReferenceDataId() {
	}

	public ReferenceDataId(String acLogicalTable, String acElement, String dsElement, String acCreationUser,
			Date tsCreation, String acLastUpdateUser, Date tsLastUpdate) {
		this.acLogicalTable = acLogicalTable;
		this.acElement = acElement;
		this.dsElement = dsElement;
		this.acCreationUser = acCreationUser;
		this.tsCreation = tsCreation;
		this.acLastUpdateUser = acLastUpdateUser;
		this.tsLastUpdate = tsLastUpdate;
	}

	public String getAcLogicalTable() {
		return this.acLogicalTable;
	}

	public void setAcLogicalTable(String acLogicalTable) {
		this.acLogicalTable = acLogicalTable;
	}

	public String getAcElement() {
		return this.acElement;
	}

	public void setAcElement(String acElement) {
		this.acElement = acElement;
	}

	public String getDsElement() {
		return this.dsElement;
	}

	public void setDsElement(String dsElement) {
		this.dsElement = dsElement;
	}

	public String getAcCreationUser() {
		return this.acCreationUser;
	}

	public void setAcCreationUser(String acCreationUser) {
		this.acCreationUser = acCreationUser;
	}

	public Date getTsCreation() {
		return this.tsCreation;
	}

	public void setTsCreation(Date tsCreation) {
		this.tsCreation = tsCreation;
	}

	public String getAcLastUpdateUser() {
		return this.acLastUpdateUser;
	}

	public void setAcLastUpdateUser(String acLastUpdateUser) {
		this.acLastUpdateUser = acLastUpdateUser;
	}

	public Date getTsLastUpdate() {
		return this.tsLastUpdate;
	}

	public void setTsLastUpdate(Date tsLastUpdate) {
		this.tsLastUpdate = tsLastUpdate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ReferenceDataId))
			return false;
		ReferenceDataId castOther = (ReferenceDataId) other;

		return ((this.getAcLogicalTable() == castOther.getAcLogicalTable())
				|| (this.getAcLogicalTable() != null && castOther.getAcLogicalTable() != null
						&& this.getAcLogicalTable().equals(castOther.getAcLogicalTable())))
				&& ((this.getAcElement() == castOther.getAcElement()) || (this.getAcElement() != null
						&& castOther.getAcElement() != null && this.getAcElement().equals(castOther.getAcElement())))
				&& ((this.getDsElement() == castOther.getDsElement()) || (this.getDsElement() != null
						&& castOther.getDsElement() != null && this.getDsElement().equals(castOther.getDsElement())))
				&& ((this.getAcCreationUser() == castOther.getAcCreationUser())
						|| (this.getAcCreationUser() != null && castOther.getAcCreationUser() != null
								&& this.getAcCreationUser().equals(castOther.getAcCreationUser())))
				&& ((this.getTsCreation() == castOther.getTsCreation()) || (this.getTsCreation() != null
						&& castOther.getTsCreation() != null && this.getTsCreation().equals(castOther.getTsCreation())))
				&& ((this.getAcLastUpdateUser() == castOther.getAcLastUpdateUser())
						|| (this.getAcLastUpdateUser() != null && castOther.getAcLastUpdateUser() != null
								&& this.getAcLastUpdateUser().equals(castOther.getAcLastUpdateUser())))
				&& ((this.getTsLastUpdate() == castOther.getTsLastUpdate())
						|| (this.getTsLastUpdate() != null && castOther.getTsLastUpdate() != null
								&& this.getTsLastUpdate().equals(castOther.getTsLastUpdate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getAcLogicalTable() == null ? 0 : this.getAcLogicalTable().hashCode());
		result = 37 * result + (getAcElement() == null ? 0 : this.getAcElement().hashCode());
		result = 37 * result + (getDsElement() == null ? 0 : this.getDsElement().hashCode());
		result = 37 * result + (getAcCreationUser() == null ? 0 : this.getAcCreationUser().hashCode());
		result = 37 * result + (getTsCreation() == null ? 0 : this.getTsCreation().hashCode());
		result = 37 * result + (getAcLastUpdateUser() == null ? 0 : this.getAcLastUpdateUser().hashCode());
		result = 37 * result + (getTsLastUpdate() == null ? 0 : this.getTsLastUpdate().hashCode());
		return result;
	}

}
