package model;
// Generated Aug 30, 2017 2:20:17 PM by Hibernate Tools 3.5.0.Final

/**
 * ReferenceData generated by hbm2java
 */
public class ReferenceData implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9185680705829693655L;
	private ReferenceDataId id;

	public ReferenceData() {
	}

	public ReferenceData(ReferenceDataId id) {
		this.id = id;
	}

	public ReferenceDataId getId() {
		return this.id;
	}

	public void setId(ReferenceDataId id) {
		this.id = id;
	}

}
