package model;
// Generated Aug 28, 2017 5:08:27 PM by Hibernate Tools 3.5.0.Final

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

/**
 * TransactionDetail generated by hbm2java
 */
public class TransactionDetail implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3569813412566960683L;
	private BigDecimal sqTransaction;
	private String acAccount;
	private String acCompany;
	private String acBalanceType;
	private String acBalanceSubtype;
	private BigDecimal sqOperation;
	private String acOperationType;
	private Date dtTransaction;
	private String acCreditDebit;
	private BigDecimal amTransaction;
	private String acCurrency;
	private String acPolicyNumber;
	private String acClaimNumber;
	private String acOriginalReceiptNumber;
	private BigDecimal sqReceipt;
	private String acCreationUser;
	private Serializable tsCreation;
	private String acLastUpdateUser;
	private Serializable tsLastUpdate;

	public TransactionDetail() {
	}

	public TransactionDetail(BigDecimal sqTransaction, String acCompany, String acBalanceType, String acBalanceSubtype,
			BigDecimal sqOperation, String acOperationType, String acCreditDebit, String acCurrency,
			String acCreationUser, Serializable tsCreation, String acLastUpdateUser, Serializable tsLastUpdate) {
		this.sqTransaction = sqTransaction;
		this.acCompany = acCompany;
		this.acBalanceType = acBalanceType;
		this.acBalanceSubtype = acBalanceSubtype;
		this.sqOperation = sqOperation;
		this.acOperationType = acOperationType;
		this.acCreditDebit = acCreditDebit;
		this.acCurrency = acCurrency;
		this.acCreationUser = acCreationUser;
		this.tsCreation = tsCreation;
		this.acLastUpdateUser = acLastUpdateUser;
		this.tsLastUpdate = tsLastUpdate;
	}

	public TransactionDetail(BigDecimal sqTransaction, String acAccount, String acCompany, String acBalanceType,
			String acBalanceSubtype, BigDecimal sqOperation, String acOperationType, Date dtTransaction,
			String acCreditDebit, BigDecimal amTransaction, String acCurrency, String acPolicyNumber,
			String acClaimNumber, String acOriginalReceiptNumber, BigDecimal sqReceipt, String acCreationUser,
			Serializable tsCreation, String acLastUpdateUser, Serializable tsLastUpdate) {
		this.sqTransaction = sqTransaction;
		this.acAccount = acAccount;
		this.acCompany = acCompany;
		this.acBalanceType = acBalanceType;
		this.acBalanceSubtype = acBalanceSubtype;
		this.sqOperation = sqOperation;
		this.acOperationType = acOperationType;
		this.dtTransaction = dtTransaction;
		this.acCreditDebit = acCreditDebit;
		this.amTransaction = amTransaction;
		this.acCurrency = acCurrency;
		this.acPolicyNumber = acPolicyNumber;
		this.acClaimNumber = acClaimNumber;
		this.acOriginalReceiptNumber = acOriginalReceiptNumber;
		this.sqReceipt = sqReceipt;
		this.acCreationUser = acCreationUser;
		this.tsCreation = tsCreation;
		this.acLastUpdateUser = acLastUpdateUser;
		this.tsLastUpdate = tsLastUpdate;
	}

	public BigDecimal getSqTransaction() {
		return this.sqTransaction;
	}

	public void setSqTransaction(BigDecimal sqTransaction) {
		this.sqTransaction = sqTransaction;
	}

	public String getAcAccount() {
		return this.acAccount;
	}

	public void setAcAccount(String acAccount) {
		this.acAccount = acAccount;
	}

	public String getAcCompany() {
		return this.acCompany;
	}

	public void setAcCompany(String acCompany) {
		this.acCompany = acCompany;
	}

	public String getAcBalanceType() {
		return this.acBalanceType;
	}

	public void setAcBalanceType(String acBalanceType) {
		this.acBalanceType = acBalanceType;
	}

	public String getAcBalanceSubtype() {
		return this.acBalanceSubtype;
	}

	public void setAcBalanceSubtype(String acBalanceSubtype) {
		this.acBalanceSubtype = acBalanceSubtype;
	}

	public BigDecimal getSqOperation() {
		return this.sqOperation;
	}

	public void setSqOperation(BigDecimal sqOperation) {
		this.sqOperation = sqOperation;
	}

	public String getAcOperationType() {
		return this.acOperationType;
	}

	public void setAcOperationType(String acOperationType) {
		this.acOperationType = acOperationType;
	}

	public Date getDtTransaction() {
		return this.dtTransaction;
	}

	public void setDtTransaction(Date dtTransaction) {
		this.dtTransaction = dtTransaction;
	}

	public String getAcCreditDebit() {
		return this.acCreditDebit;
	}

	public void setAcCreditDebit(String acCreditDebit) {
		this.acCreditDebit = acCreditDebit;
	}

	public BigDecimal getAmTransaction() {
		return this.amTransaction;
	}

	public void setAmTransaction(BigDecimal amTransaction) {
		this.amTransaction = amTransaction;
	}

	public String getAcCurrency() {
		return this.acCurrency;
	}

	public void setAcCurrency(String acCurrency) {
		this.acCurrency = acCurrency;
	}

	public String getAcPolicyNumber() {
		return this.acPolicyNumber;
	}

	public void setAcPolicyNumber(String acPolicyNumber) {
		this.acPolicyNumber = acPolicyNumber;
	}

	public String getAcClaimNumber() {
		return this.acClaimNumber;
	}

	public void setAcClaimNumber(String acClaimNumber) {
		this.acClaimNumber = acClaimNumber;
	}

	public String getAcOriginalReceiptNumber() {
		return this.acOriginalReceiptNumber;
	}

	public void setAcOriginalReceiptNumber(String acOriginalReceiptNumber) {
		this.acOriginalReceiptNumber = acOriginalReceiptNumber;
	}

	public BigDecimal getSqReceipt() {
		return this.sqReceipt;
	}

	public void setSqReceipt(BigDecimal sqReceipt) {
		this.sqReceipt = sqReceipt;
	}

	public String getAcCreationUser() {
		return this.acCreationUser;
	}

	public void setAcCreationUser(String acCreationUser) {
		this.acCreationUser = acCreationUser;
	}

	public Serializable getTsCreation() {
		return this.tsCreation;
	}

	public void setTsCreation(Serializable tsCreation) {
		this.tsCreation = tsCreation;
	}

	public String getAcLastUpdateUser() {
		return this.acLastUpdateUser;
	}

	public void setAcLastUpdateUser(String acLastUpdateUser) {
		this.acLastUpdateUser = acLastUpdateUser;
	}

	public Serializable getTsLastUpdate() {
		return this.tsLastUpdate;
	}

	public void setTsLastUpdate(Serializable tsLastUpdate) {
		this.tsLastUpdate = tsLastUpdate;
	}

}
